project_id = "tglgxdfqfwspykzxwxgy"
[functions.auth-phone-verify]
enabled = true
verify_jwt = true
import_map = "./functions/auth-phone-verify/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/auth-phone-verify/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/auth-phone-verify/*.html" ]

[functions.notify-chat-message]
enabled = true
verify_jwt = true
entrypoint = "./functions/notify-chat-message/index.ts"

[functions.notify-seminar-event]
enabled = true
verify_jwt = true
entrypoint = "./functions/notify-seminar-event/index.ts"

[functions.send-seminar-reminders]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-seminar-reminders/index.ts"

[functions.retry-notification]
enabled = true
verify_jwt = false
entrypoint = "./functions/retry-notification/index.ts"
